#!/usr/bin/python


print "Content-type:text/html\r\n\r\n"
print "<html>"
print "<head>"
print "<title>Shopper Registration Screen</title>"
print "</head>"

print "<body>"
print "<h1>Registration</h1><br>"
#print "<form action='http://localhost/~coursework/cgi-bin/pass_verification.py' method='post'>"
print "<form name='reg'>"
print "First Name: <input type='text' name='first_name' required><br>"
print "Last Name: <input type='text' name='last_name' required><br>"  
print "User ID: <input type='text' name='user_id' required><br>"
print "Password: <input type='password' name='passwd' required><br>"
print "Confirm Password: <input type='password' name=conf_passwd required><br>"
print "Email: <input type='text' name='email' required><br>"
print "<input type = 'submit' onclick='return validatePassword();' value='Register'/>"
print "<script type='text/javascript'>"
print "function validatePassword(){"  
print "if(reg.passwd.value != reg.conf_passwd.value){"
#print "alert('Passwords Does Not Match!'); return false;} else {"
print "reg.conf_passwd.setCustomValidity('Passwords Do not Match!');} else {"
print "reg.conf_passwd.setCustomValidity(''); return true;}}"
#print "passwd.onchange = validatePasswd; conf_passwd.onkeyup = validatePassword;
print "</script>"
print "</form>"
print "</body>"
print "</html>"
